spring:
  sql:
    init:
      encoding: UTF-8
      mode: always
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
