-- Oracleの場合は追加
--DROP TABLE TODO CASCADE CONSTRAINTS;

-- テーブル作成
CREATE TABLE TODO
(
    ID    NUMBER(15) GENERATED ALWAYS AS IDENTITY,
    TITLE VARCHAR2(100 Byte),
    DONE  BOOLEAN    -- Oracleの場合は、NUMBER(1)
);
ALTER TABLE TODO ADD CONSTRAINT PK_TODO PRIMARY KEY (ID);
